configs:

  myLibSvc:
    runInLocal: '{{ .GetValue "runMyLibSvcInLocal" }}'
    ports: |
      {{ .GetEnv "APP_HTTP_PORT" }}

  myLibSvcContainer:
    useImagePrefix: true
    imageName: my-app
    containerName: myLibSvc
    localhost: host.docker.internal
    checkCommand: |
      echo "check myLibSvc"
    volumes: |


  startMyLibSvc:
    start: |
      . "{{ .GetProjectPath "zaruba-tasks/myLibSvc/bash/run.sh" }}" "{{ .GetProjectPath "zaruba-tasks/myLibSvc/bash/application.sh" }}"
    check: |
      echo "check myLibSvc"

  prepareMyLibSvc:
    start: |
      . "{{ .GetProjectPath "zaruba-tasks/myLibSvc/bash/run.sh" }}" "{{ .GetProjectPath "zaruba-tasks/myLibSvc/bash/preparation.sh" }}"

  testMyLibSvc:
    start: |
      . "{{ .GetProjectPath "zaruba-tasks/myLibSvc/bash/run.sh" }}" "{{ .GetProjectPath "zaruba-tasks/myLibSvc/bash/test.sh" }}"

  migrateMyLibSvc:
    start: |
      . "{{ .GetProjectPath "zaruba-tasks/myLibSvc/bash/run.sh" }}" "{{ .GetProjectPath "zaruba-tasks/myLibSvc/bash/migration.sh" }}"
