configs:

  myLibSvc:
    runInLocal: '{{ .GetValue "runMyLibSvcInLocal" }}'
    ports: |
      {{ .GetEnv "APP_HTTP_PORT" }}

  myLibSvcContainer:
    useImagePrefix: true
    imageName: my-app
    containerName: myLibSvc
    escapedEnvs: |
      APP_UI_BACKEND_URL
    localhost: host.docker.internal
    checkCommand: |
      echo "check myLibSvc"
    volumes: ""

  startMyLibSvc:
    start: |
      . "{{ .GetProjectPath "zaruba-tasks/myLibSvc/bash/run.sh" }}" "{{ .GetProjectPath "zaruba-tasks/myLibSvc/bash/application.sh" }}"
    check: |
      echo "check myLibSvc"

  prepareMyLibSvc:
    start: |-
      echo "Done"

  testMyLibSvc:
    start: |
      . "{{ .GetProjectPath "zaruba-tasks/myLibSvc/bash/run.sh" }}" "{{ .GetProjectPath "zaruba-tasks/myLibSvc/bash/test.sh" }}"

  migrateMyLibSvc:
    start: |
      . "{{ .GetProjectPath "zaruba-tasks/myLibSvc/bash/run.sh" }}" "{{ .GetProjectPath "zaruba-tasks/myLibSvc/bash/migration.sh" }}"

