{{- if and (.Values.service.enabled) (gt (len (.Values.ports)) 0) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "my-app.selectorLabels" . | nindent 4 }}
{{- end }}
