"""20221031211047 quiet_water

Revision ID: 73082377a89c
Revises: 2c643d4333f3
Create Date: 2022-10-31 21:10:47.633216

"""
from alembic import op
import sqlalchemy as sa
import os


# revision identifiers, used by Alembic.
revision = '73082377a89c'
down_revision = '2c643d4333f3'
branch_labels = None
depends_on = None


def run_migration() -> bool:
    return os.getenv('MIGRATION_RUN_ALL', '0') != '0' or os.getenv('APP_ENABLE_LIBRARY_MODULE', '1') != '0'


def upgrade() -> None:
    if not run_migration():
        return None
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('synopsis', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_author'), 'books', ['author'], unique=False)
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_index(op.f('ix_books_synopsis'), 'books', ['synopsis'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.drop_index('ix_activities_activity', table_name='activities')
    op.drop_index('ix_activities_id', table_name='activities')
    op.drop_index('ix_activities_object', table_name='activities')
    op.drop_index('ix_activities_row_id', table_name='activities')
    op.drop_index('ix_activities_user_id', table_name='activities')
    op.drop_table('activities')
    op.create_index(op.f('ix_roles_json_permissions'), 'roles', ['json_permissions'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    if not run_migration():
        return None
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_json_permissions'), table_name='roles')
    op.create_table('activities',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('activity', sa.VARCHAR(length=255), nullable=False),
    sa.Column('object', sa.VARCHAR(length=255), nullable=True),
    sa.Column('row_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('json_row', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=36), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activities_user_id', 'activities', ['user_id'], unique=False)
    op.create_index('ix_activities_row_id', 'activities', ['row_id'], unique=False)
    op.create_index('ix_activities_object', 'activities', ['object'], unique=False)
    op.create_index('ix_activities_id', 'activities', ['id'], unique=False)
    op.create_index('ix_activities_activity', 'activities', ['activity'], unique=False)
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_synopsis'), table_name='books')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_index(op.f('ix_books_author'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
