configs:

  prepareMyBackendDeployment:
    useImagePrefix: true
    imagePrefix: '{{ .GetValue "defaultImagePrefix" }}'
    imageName: my-app
    imageTag: '{{ if .GetValue "ztplDeploymentImageTag" }}{{ .GetValue "ztplDeploymentImageTag" }}{{ else }}latest{{ end }}'
    ports: |
      3002
    start: |
      . "{{ .GetProjectPath "zaruba-tasks/myBackendDeployment/bash/run.sh" }}" "{{ .GetProjectPath "zaruba-tasks/myBackendDeployment/bash/preparation.sh" }}"
      DEPLOYMENT_CONFIG={}
      IMAGE_REPOSITORY="{{ .GetDockerImageName }}"
      IMAGE_TAG="{{ if .GetConfig "imageTag" }}{{ .GetConfig "imageTag" }}{{ else }}latest{{ end }}"
      RAW_ENVS='{{ .Util.Json.FromStringDict .GetEnvs }}'
      . '{{ .GetProjectPath "zaruba-tasks/myBackendDeployment/bash/util.sh" }}'
      . '{{ .GetProjectPath "zaruba-tasks/myBackendDeployment/bash/prepareVariables.sh" }}'
      echo "${_YELLOW}${_CONSTRUCTION_ICON} Deployment config:${_NORMAL} ${DEPLOYMENT_CONFIG}"
      "${ZARUBA_BIN}" json print "${DEPLOYMENT_CONFIG}" '{{ .GetProjectPath "myBackendDeployment/config/config.json" }}'
      . '{{ .GetProjectPath "zaruba-tasks/myBackendDeployment/bash/prepareChart.sh" }}'