configs:

  myRabbitmq:
    runInLocal: '{{ .GetValue "runMyRabbitmqInLocal" }}'
    ports: |
      {{ .GetEnv "RABBITMQ_NODE_PORT_NUMBER" }}
      {{ .GetEnv "RABBITMQ_NODE_SSL_PORT_NUMBER" }}
      15672

  myRabbitmqContainer:
    useImagePrefix: true
    imageName: my-rabbitmq
    containerName: myRabbitmq
    localhost: host.docker.internal
    afterCheck: sleep 3
    checkCommand: |
      rabbitmqctl await_startup
    command : |

    volumes: |
